import { Request, Response } from "express";
import asyncHandler from "express-async-handler";
import bcrypt from "bcryptjs";
import jwt, { JwtPayload } from "jsonwebtoken";
import { User } from "../models/index.js";
import { generateToken } from "../utils/generateToken.util.js";
import { CustomRequest } from "../interfaces/index.js";
import { createHash, randomBytes } from "crypto";

const registerUser = asyncHandler(async (req: Request, res: Response) => {
  const { username, email, password } = req.body;

  if (!username || !email || !password) {
    res.status(400);
    throw new Error(`Please fill in all required fields`);
  }

  if (password.length < 6) {
    res.status(400);
    throw new Error(`Password must be upto 6 characters`);
  }

  const userExists = await User.findOne({ email });

  if (userExists) {
    res.status(400);
    throw new Error("User already exists");
  }

  const user = await User.create({
    username,
    email,
    password,
  });

  if (user) {
    const { _id, username, email, photo, authMethod } = user;
    generateToken(res, _id);
    res.status(201).json({ _id, username, email, photo, authMethod });
  } else {
    res.status(400);
    throw new Error(`Invalid user data`);
  }
});

const loginUser = asyncHandler(async (req: Request, res: Response) => {
  const { email, password } = req.body;

  if (!email || !password) {
    res.status(400);
    throw new Error("Please add email and password");
  }

  const user = await User.findOne({ email });

  if (!user) {
    res.status(400);
    throw new Error("User not found, please signup");
  }

  const passwordIsCorrect = await bcrypt.compare(password, user.password);

  if (passwordIsCorrect) {
    generateToken(res, user._id);
  }
  if (user && passwordIsCorrect) {
    const { _id, username, email, photo, authMethod } = user;
    res.status(200).json({
      _id,
      username,
      email,
      photo,
      authMethod,
    });
  } else {
    res.status(401);
    throw new Error("Invalid user data");
  }
});

const loginWithGoogle = asyncHandler(async (req: Request, res: Response) => {
  const { username, email, photo, authMethod } = req.body;

  const userExists = await User.findOne({ email });

  if (!userExists) {
    let autoGeneratedName =
      username.replace(/\s/g, "") + Math.floor(Math.random() * 100);
    const user = await User.create({
      username: autoGeneratedName,
      email,
      photo,
      authMethod,
    });

    if (user) {
      const { _id, username, email, photo, authMethod } = user;

      generateToken(res, _id);

      res.status(201).json({ _id, username, email, photo, authMethod });
    } else {
      res.status(400);
      throw new Error(`Error occured while Logging with Google`);
    }
  } else {
    const { _id, username, email, photo, authMethod } = userExists;

    generateToken(res, userExists._id);

    res.status(200).json({
      _id,
      username,
      email,
      photo,
      authMethod,
    });
  }
});

const logoutUser = asyncHandler(async (req: Request, res: Response) => {
  res.cookie("jwt", "", {
    httpOnly: true,
    expires: new Date(0),
  });
  res.status(200).json({ message: "Logged out successfully" });
});

const getUser = asyncHandler(async (req: CustomRequest, res: Response) => {
  const { _id, username, email, photo } = req.user;
  const user = { _id, username, email, photo };
  res.status(200).json(user);
});

const updateUser = asyncHandler(async (req: CustomRequest, res: Response) => {
  const user = await User.findById(req.user._id);

  if (user) {
    const { username, email, photo } = user;
    user.email = email;
    user.username = req.body.username || username;
    user.photo = req.body.photo || photo;

    const updatedUser = await user.save();
    res.status(200).json({
      _id: updatedUser._id,
      username: updatedUser.username,
      email: updatedUser.email,
      photo: updatedUser.photo,
    });
  } else {
    res.status(404);
    throw new Error("User not found");
  }
});

const getLoggedInStatus = async (req: Request, res: Response) => {
  const token = req.cookies.jwt;
  if (!token) {
    return res.json(false);
  }

  // Verify Token
  const verified = jwt.verify(token, process.env.JWT_SECRET);
  if (verified) {
    return res.json(true);
  }
  return res.json(false);
};

const changePassword = asyncHandler(
  async (req: CustomRequest, res: Response) => {
    const user = await User.findById(req.user._id);
    const { oldPassword, password } = req.body;

    if (!user) {
      res.status(400);
      throw new Error("User not found, please signup");
    }

    // Validation
    if (!oldPassword || !password) {
      res.status(400);
      throw new Error("Please add old and new password");
    }

    // check if old password matches password in DB
    const passwordIsCorrect = await bcrypt.compare(oldPassword, user.password);

    // Save new password
    if (user && passwordIsCorrect) {
      user.password = password;
      await user.save();
      res.status(200).json({ message: "Password changed successfully" });
    } else {
      res.status(400);
      throw new Error("Old password is incorrect");
    }
  }
);

const forgetPassword = () => {};
const resetPassword = () => {};

export {
  registerUser,
  loginUser,
  loginWithGoogle,
  logoutUser,
  getUser,
  updateUser,
  getLoggedInStatus,
  changePassword,
  forgetPassword,
  resetPassword,
};
